#!/bin/bash
path=/home/jbn/compilation/tests
echo -e "function ff0 : read X % nop % write X" > tests/wh/testProf$1.wh
i=1
while [ $i -lt $1 ]
do
	echo -e "function ff$i : read X % nop % write X" >> tests/wh/testProf$1.wh
	i=$[$i+1]
done
