/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.validation;

import org.xtext.comp.validation.AbstractWhValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WhValidator extends AbstractWhValidator {
}
