/*
 * generated by Xtext 2.10.0
 */
package org.xtext.comp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhStandaloneSetup extends WhStandaloneSetupGenerated {

	def static void doSetup() {
		new WhStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
