/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp;

import org.xtext.comp.WhStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhStandaloneSetup extends WhStandaloneSetupGenerated {
  public static void doSetup() {
    WhStandaloneSetup _whStandaloneSetup = new WhStandaloneSetup();
    _whStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
