/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getVarSimple <em>Var Simple</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getSym <em>Sym</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprSimple()
 * @model
 * @generated
 */
public interface ExprSimple extends Expr
{
  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

  /**
   * Returns the value of the '<em><b>Var Simple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Simple</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Simple</em>' attribute.
   * @see #setVarSimple(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_VarSimple()
   * @model
   * @generated
   */
  String getVarSimple();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getVarSimple <em>Var Simple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Simple</em>' attribute.
   * @see #getVarSimple()
   * @generated
   */
  void setVarSimple(String value);

  /**
   * Returns the value of the '<em><b>Sym</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sym</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sym</em>' attribute.
   * @see #setSym(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_Sym()
   * @model
   * @generated
   */
  String getSym();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getSym <em>Sym</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sym</em>' attribute.
   * @see #getSym()
   * @generated
   */
  void setSym(String value);

} // ExprSimple
