/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Hd</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprHd#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprHd()
 * @model
 * @generated
 */
public interface ExprHd extends Expr
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference.
   * @see #setArg(Expr)
   * @see org.xtext.comp.wh.WhPackage#getExprHd_Arg()
   * @model containment="true"
   * @generated
   */
  Expr getArg();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprHd#getArg <em>Arg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' containment reference.
   * @see #getArg()
   * @generated
   */
  void setArg(Expr value);

} // ExprHd
