/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Sym</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprSym#getArg1 <em>Arg1</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSym#getArg2 <em>Arg2</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprSym()
 * @model
 * @generated
 */
public interface ExprSym extends EObject
{
  /**
   * Returns the value of the '<em><b>Arg1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg1</em>' attribute.
   * @see #setArg1(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSym_Arg1()
   * @model
   * @generated
   */
  String getArg1();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSym#getArg1 <em>Arg1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg1</em>' attribute.
   * @see #getArg1()
   * @generated
   */
  void setArg1(String value);

  /**
   * Returns the value of the '<em><b>Arg2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.wh.Expr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg2</em>' containment reference list.
   * @see org.xtext.comp.wh.WhPackage#getExprSym_Arg2()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getArg2();

} // ExprSym
