/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.comp.wh.WhFactory
 * @model kind="package"
 * @generated
 */
public interface WhPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "wh";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/comp/Wh";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "wh";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WhPackage eINSTANCE = org.xtext.comp.wh.impl.WhPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.WhImpl <em>Wh</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.WhImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getWh()
   * @generated
   */
  int WH = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WH__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Wh</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ProgramImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNCTIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.FunctionImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__DEFINITION = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.DefinitionImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__INPUT = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__COMMANDS = 1;

  /**
   * The feature id for the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__OUTPUT = 2;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.InputImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getInput()
   * @generated
   */
  int INPUT = 4;

  /**
   * The feature id for the '<em><b>Vars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__VARS = 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.OutputImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 5;

  /**
   * The feature id for the '<em><b>Vars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__VARS = 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.CommandsImpl <em>Commands</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.CommandsImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getCommands()
   * @generated
   */
  int COMMANDS = 6;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Commands</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.CommandImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 7;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__CMD = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.IfImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getIf()
   * @generated
   */
  int IF = 8;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__EXPR = 0;

  /**
   * The feature id for the '<em><b>Commands1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COMMANDS1 = 1;

  /**
   * The feature id for the '<em><b>Commands2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COMMANDS2 = 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.NopImpl <em>Nop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.NopImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getNop()
   * @generated
   */
  int NOP = 9;

  /**
   * The feature id for the '<em><b>Nop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP__NOP = 0;

  /**
   * The number of structural features of the '<em>Nop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.AffectImpl <em>Affect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.AffectImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getAffect()
   * @generated
   */
  int AFFECT = 10;

  /**
   * The feature id for the '<em><b>Vars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECT__VARS = 0;

  /**
   * The feature id for the '<em><b>Exprs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECT__EXPRS = 1;

  /**
   * The number of structural features of the '<em>Affect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ForImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getFor()
   * @generated
   */
  int FOR = 11;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__EXPR = 0;

  /**
   * The feature id for the '<em><b>Cmds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__CMDS = 1;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.WhileImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 12;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__EXPR = 0;

  /**
   * The feature id for the '<em><b>Cmds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__CMDS = 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 13;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__EXPR_EQ = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__EXPR = 1;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprSimpleImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprSimple()
   * @generated
   */
  int EXPR_SIMPLE = 14;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__STR = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var Simple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__VAR_SIMPLE = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sym</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__SYM = EXPR_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Name Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__NAME_FUNCTION = EXPR_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__VARS = EXPR_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Expr Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE_FEATURE_COUNT = EXPR_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprAndImpl <em>Expr And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprAndImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprAnd()
   * @generated
   */
  int EXPR_AND = 15;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_AND__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_AND__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_AND__ARG1 = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arg2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_AND__ARG2 = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_AND_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprOrImpl <em>Expr Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprOrImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprOr()
   * @generated
   */
  int EXPR_OR = 16;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_OR__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_OR__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_OR__ARG1 = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arg2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_OR__ARG2 = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_OR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprConsImpl <em>Expr Cons</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprConsImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprCons()
   * @generated
   */
  int EXPR_CONS = 17;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONS__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONS__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONS__ARG = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr Cons</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprListImpl <em>Expr List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprListImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprList()
   * @generated
   */
  int EXPR_LIST = 18;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LIST__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LIST__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LIST__ARG = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LIST_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprHdImpl <em>Expr Hd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprHdImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprHd()
   * @generated
   */
  int EXPR_HD = 19;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_HD__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_HD__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_HD__ARG = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr Hd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_HD_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprTlImpl <em>Expr Tl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprTlImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprTl()
   * @generated
   */
  int EXPR_TL = 20;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_TL__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_TL__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_TL__ARG = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr Tl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_TL_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprSymImpl <em>Expr Sym</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprSymImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprSym()
   * @generated
   */
  int EXPR_SYM = 21;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SYM__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SYM__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SYM__ARG1 = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arg2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SYM__ARG2 = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Sym</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SYM_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprNotImpl <em>Expr Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprNotImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprNot()
   * @generated
   */
  int EXPR_NOT = 22;

  /**
   * The feature id for the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_NOT__EXPR_EQ = EXPR__EXPR_EQ;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_NOT__EXPR = EXPR__EXPR;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_NOT__ARG1 = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_NOT_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.comp.wh.impl.ExprEqImpl <em>Expr Eq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.comp.wh.impl.ExprEqImpl
   * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprEq()
   * @generated
   */
  int EXPR_EQ = 23;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_EQ__ARG1 = 0;

  /**
   * The feature id for the '<em><b>Arg2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_EQ__ARG2 = 1;

  /**
   * The number of structural features of the '<em>Expr Eq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_EQ_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Wh <em>Wh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wh</em>'.
   * @see org.xtext.comp.wh.Wh
   * @generated
   */
  EClass getWh();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.Wh#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.comp.wh.Wh#getElements()
   * @see #getWh()
   * @generated
   */
  EReference getWh_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.comp.wh.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.Program#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see org.xtext.comp.wh.Program#getFunctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Functions();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.comp.wh.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.comp.wh.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Function#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Definition</em>'.
   * @see org.xtext.comp.wh.Function#getDefinition()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Definition();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see org.xtext.comp.wh.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Definition#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see org.xtext.comp.wh.Definition#getInput()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Input();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Definition#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands</em>'.
   * @see org.xtext.comp.wh.Definition#getCommands()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Commands();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Definition#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Output</em>'.
   * @see org.xtext.comp.wh.Definition#getOutput()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Output();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.xtext.comp.wh.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.comp.wh.Input#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vars</em>'.
   * @see org.xtext.comp.wh.Input#getVars()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.xtext.comp.wh.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.comp.wh.Output#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vars</em>'.
   * @see org.xtext.comp.wh.Output#getVars()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Commands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commands</em>'.
   * @see org.xtext.comp.wh.Commands
   * @generated
   */
  EClass getCommands();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.Commands#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.comp.wh.Commands#getCommands()
   * @see #getCommands()
   * @generated
   */
  EReference getCommands_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.comp.wh.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Command#getCmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd</em>'.
   * @see org.xtext.comp.wh.Command#getCmd()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Cmd();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.xtext.comp.wh.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.If#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.comp.wh.If#getExpr()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Expr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.If#getCommands1 <em>Commands1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands1</em>'.
   * @see org.xtext.comp.wh.If#getCommands1()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Commands1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.If#getCommands2 <em>Commands2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands2</em>'.
   * @see org.xtext.comp.wh.If#getCommands2()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Commands2();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Nop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nop</em>'.
   * @see org.xtext.comp.wh.Nop
   * @generated
   */
  EClass getNop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.Nop#getNop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nop</em>'.
   * @see org.xtext.comp.wh.Nop#getNop()
   * @see #getNop()
   * @generated
   */
  EAttribute getNop_Nop();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Affect <em>Affect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affect</em>'.
   * @see org.xtext.comp.wh.Affect
   * @generated
   */
  EClass getAffect();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.comp.wh.Affect#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vars</em>'.
   * @see org.xtext.comp.wh.Affect#getVars()
   * @see #getAffect()
   * @generated
   */
  EAttribute getAffect_Vars();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.Affect#getExprs <em>Exprs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exprs</em>'.
   * @see org.xtext.comp.wh.Affect#getExprs()
   * @see #getAffect()
   * @generated
   */
  EReference getAffect_Exprs();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see org.xtext.comp.wh.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.For#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.comp.wh.For#getExpr()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Expr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.For#getCmds <em>Cmds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds</em>'.
   * @see org.xtext.comp.wh.For#getCmds()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Cmds();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see org.xtext.comp.wh.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.While#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.comp.wh.While#getExpr()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Expr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.While#getCmds <em>Cmds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds</em>'.
   * @see org.xtext.comp.wh.While#getCmds()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Cmds();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.xtext.comp.wh.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Expr#getExprEq <em>Expr Eq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Eq</em>'.
   * @see org.xtext.comp.wh.Expr#getExprEq()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_ExprEq();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.Expr#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.comp.wh.Expr#getExpr()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Expr();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprSimple <em>Expr Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Simple</em>'.
   * @see org.xtext.comp.wh.ExprSimple
   * @generated
   */
  EClass getExprSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.ExprSimple#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.xtext.comp.wh.ExprSimple#getStr()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Str();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.ExprSimple#getVarSimple <em>Var Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Simple</em>'.
   * @see org.xtext.comp.wh.ExprSimple#getVarSimple()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_VarSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.ExprSimple#getSym <em>Sym</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sym</em>'.
   * @see org.xtext.comp.wh.ExprSimple#getSym()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Sym();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.ExprSimple#getNameFunction <em>Name Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name Function</em>'.
   * @see org.xtext.comp.wh.ExprSimple#getNameFunction()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_NameFunction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprSimple#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vars</em>'.
   * @see org.xtext.comp.wh.ExprSimple#getVars()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprAnd <em>Expr And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr And</em>'.
   * @see org.xtext.comp.wh.ExprAnd
   * @generated
   */
  EClass getExprAnd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprAnd#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg1</em>'.
   * @see org.xtext.comp.wh.ExprAnd#getArg1()
   * @see #getExprAnd()
   * @generated
   */
  EReference getExprAnd_Arg1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprAnd#getArg2 <em>Arg2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg2</em>'.
   * @see org.xtext.comp.wh.ExprAnd#getArg2()
   * @see #getExprAnd()
   * @generated
   */
  EReference getExprAnd_Arg2();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprOr <em>Expr Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Or</em>'.
   * @see org.xtext.comp.wh.ExprOr
   * @generated
   */
  EClass getExprOr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprOr#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg1</em>'.
   * @see org.xtext.comp.wh.ExprOr#getArg1()
   * @see #getExprOr()
   * @generated
   */
  EReference getExprOr_Arg1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprOr#getArg2 <em>Arg2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg2</em>'.
   * @see org.xtext.comp.wh.ExprOr#getArg2()
   * @see #getExprOr()
   * @generated
   */
  EReference getExprOr_Arg2();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprCons <em>Expr Cons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Cons</em>'.
   * @see org.xtext.comp.wh.ExprCons
   * @generated
   */
  EClass getExprCons();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.ExprCons#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arg</em>'.
   * @see org.xtext.comp.wh.ExprCons#getArg()
   * @see #getExprCons()
   * @generated
   */
  EReference getExprCons_Arg();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprList <em>Expr List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr List</em>'.
   * @see org.xtext.comp.wh.ExprList
   * @generated
   */
  EClass getExprList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.ExprList#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arg</em>'.
   * @see org.xtext.comp.wh.ExprList#getArg()
   * @see #getExprList()
   * @generated
   */
  EReference getExprList_Arg();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprHd <em>Expr Hd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Hd</em>'.
   * @see org.xtext.comp.wh.ExprHd
   * @generated
   */
  EClass getExprHd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprHd#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg</em>'.
   * @see org.xtext.comp.wh.ExprHd#getArg()
   * @see #getExprHd()
   * @generated
   */
  EReference getExprHd_Arg();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprTl <em>Expr Tl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Tl</em>'.
   * @see org.xtext.comp.wh.ExprTl
   * @generated
   */
  EClass getExprTl();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprTl#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg</em>'.
   * @see org.xtext.comp.wh.ExprTl#getArg()
   * @see #getExprTl()
   * @generated
   */
  EReference getExprTl_Arg();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprSym <em>Expr Sym</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Sym</em>'.
   * @see org.xtext.comp.wh.ExprSym
   * @generated
   */
  EClass getExprSym();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.comp.wh.ExprSym#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arg1</em>'.
   * @see org.xtext.comp.wh.ExprSym#getArg1()
   * @see #getExprSym()
   * @generated
   */
  EAttribute getExprSym_Arg1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.comp.wh.ExprSym#getArg2 <em>Arg2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arg2</em>'.
   * @see org.xtext.comp.wh.ExprSym#getArg2()
   * @see #getExprSym()
   * @generated
   */
  EReference getExprSym_Arg2();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprNot <em>Expr Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Not</em>'.
   * @see org.xtext.comp.wh.ExprNot
   * @generated
   */
  EClass getExprNot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprNot#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg1</em>'.
   * @see org.xtext.comp.wh.ExprNot#getArg1()
   * @see #getExprNot()
   * @generated
   */
  EReference getExprNot_Arg1();

  /**
   * Returns the meta object for class '{@link org.xtext.comp.wh.ExprEq <em>Expr Eq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Eq</em>'.
   * @see org.xtext.comp.wh.ExprEq
   * @generated
   */
  EClass getExprEq();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprEq#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg1</em>'.
   * @see org.xtext.comp.wh.ExprEq#getArg1()
   * @see #getExprEq()
   * @generated
   */
  EReference getExprEq_Arg1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.comp.wh.ExprEq#getArg2 <em>Arg2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg2</em>'.
   * @see org.xtext.comp.wh.ExprEq#getArg2()
   * @see #getExprEq()
   * @generated
   */
  EReference getExprEq_Arg2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WhFactory getWhFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.WhImpl <em>Wh</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.WhImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getWh()
     * @generated
     */
    EClass WH = eINSTANCE.getWh();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WH__ELEMENTS = eINSTANCE.getWh_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ProgramImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FUNCTIONS = eINSTANCE.getProgram_Functions();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.FunctionImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__DEFINITION = eINSTANCE.getFunction_Definition();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.DefinitionImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__INPUT = eINSTANCE.getDefinition_Input();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__COMMANDS = eINSTANCE.getDefinition_Commands();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__OUTPUT = eINSTANCE.getDefinition_Output();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.InputImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__VARS = eINSTANCE.getInput_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.OutputImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__VARS = eINSTANCE.getOutput_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.CommandsImpl <em>Commands</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.CommandsImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getCommands()
     * @generated
     */
    EClass COMMANDS = eINSTANCE.getCommands();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDS__COMMANDS = eINSTANCE.getCommands_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.CommandImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Cmd</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__CMD = eINSTANCE.getCommand_Cmd();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.IfImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__EXPR = eINSTANCE.getIf_Expr();

    /**
     * The meta object literal for the '<em><b>Commands1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COMMANDS1 = eINSTANCE.getIf_Commands1();

    /**
     * The meta object literal for the '<em><b>Commands2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COMMANDS2 = eINSTANCE.getIf_Commands2();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.NopImpl <em>Nop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.NopImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getNop()
     * @generated
     */
    EClass NOP = eINSTANCE.getNop();

    /**
     * The meta object literal for the '<em><b>Nop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOP__NOP = eINSTANCE.getNop_Nop();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.AffectImpl <em>Affect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.AffectImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getAffect()
     * @generated
     */
    EClass AFFECT = eINSTANCE.getAffect();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECT__VARS = eINSTANCE.getAffect_Vars();

    /**
     * The meta object literal for the '<em><b>Exprs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECT__EXPRS = eINSTANCE.getAffect_Exprs();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ForImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__EXPR = eINSTANCE.getFor_Expr();

    /**
     * The meta object literal for the '<em><b>Cmds</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__CMDS = eINSTANCE.getFor_Cmds();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.WhileImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__EXPR = eINSTANCE.getWhile_Expr();

    /**
     * The meta object literal for the '<em><b>Cmds</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__CMDS = eINSTANCE.getWhile_Cmds();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Expr Eq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__EXPR_EQ = eINSTANCE.getExpr_ExprEq();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__EXPR = eINSTANCE.getExpr_Expr();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprSimpleImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprSimple()
     * @generated
     */
    EClass EXPR_SIMPLE = eINSTANCE.getExprSimple();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__STR = eINSTANCE.getExprSimple_Str();

    /**
     * The meta object literal for the '<em><b>Var Simple</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__VAR_SIMPLE = eINSTANCE.getExprSimple_VarSimple();

    /**
     * The meta object literal for the '<em><b>Sym</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__SYM = eINSTANCE.getExprSimple_Sym();

    /**
     * The meta object literal for the '<em><b>Name Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__NAME_FUNCTION = eINSTANCE.getExprSimple_NameFunction();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__VARS = eINSTANCE.getExprSimple_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprAndImpl <em>Expr And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprAndImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprAnd()
     * @generated
     */
    EClass EXPR_AND = eINSTANCE.getExprAnd();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_AND__ARG1 = eINSTANCE.getExprAnd_Arg1();

    /**
     * The meta object literal for the '<em><b>Arg2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_AND__ARG2 = eINSTANCE.getExprAnd_Arg2();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprOrImpl <em>Expr Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprOrImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprOr()
     * @generated
     */
    EClass EXPR_OR = eINSTANCE.getExprOr();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_OR__ARG1 = eINSTANCE.getExprOr_Arg1();

    /**
     * The meta object literal for the '<em><b>Arg2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_OR__ARG2 = eINSTANCE.getExprOr_Arg2();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprConsImpl <em>Expr Cons</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprConsImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprCons()
     * @generated
     */
    EClass EXPR_CONS = eINSTANCE.getExprCons();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_CONS__ARG = eINSTANCE.getExprCons_Arg();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprListImpl <em>Expr List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprListImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprList()
     * @generated
     */
    EClass EXPR_LIST = eINSTANCE.getExprList();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_LIST__ARG = eINSTANCE.getExprList_Arg();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprHdImpl <em>Expr Hd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprHdImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprHd()
     * @generated
     */
    EClass EXPR_HD = eINSTANCE.getExprHd();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_HD__ARG = eINSTANCE.getExprHd_Arg();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprTlImpl <em>Expr Tl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprTlImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprTl()
     * @generated
     */
    EClass EXPR_TL = eINSTANCE.getExprTl();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_TL__ARG = eINSTANCE.getExprTl_Arg();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprSymImpl <em>Expr Sym</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprSymImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprSym()
     * @generated
     */
    EClass EXPR_SYM = eINSTANCE.getExprSym();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SYM__ARG1 = eINSTANCE.getExprSym_Arg1();

    /**
     * The meta object literal for the '<em><b>Arg2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SYM__ARG2 = eINSTANCE.getExprSym_Arg2();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprNotImpl <em>Expr Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprNotImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprNot()
     * @generated
     */
    EClass EXPR_NOT = eINSTANCE.getExprNot();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_NOT__ARG1 = eINSTANCE.getExprNot_Arg1();

    /**
     * The meta object literal for the '{@link org.xtext.comp.wh.impl.ExprEqImpl <em>Expr Eq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.comp.wh.impl.ExprEqImpl
     * @see org.xtext.comp.wh.impl.WhPackageImpl#getExprEq()
     * @generated
     */
    EClass EXPR_EQ = eINSTANCE.getExprEq();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_EQ__ARG1 = eINSTANCE.getExprEq_Arg1();

    /**
     * The meta object literal for the '<em><b>Arg2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_EQ__ARG2 = eINSTANCE.getExprEq_Arg2();

  }

} //WhPackage
